course_name = "图像处理"
course_code = "COMP3018"
repo_type = "normal"
description = "COMP3018 - 图像处理课程资料。"

[lecturers]

[[lecturers.items]]
name = "卢光明"

[[lecturers.items.reviews]]
content = "人挺好，几乎不点名。"

[[sections]]
title = "课程内容"

[[sections.items]]
content = "中文授课，英文 PPT（有少量中文注解）。"

[[sections]]
title = "关于考试"

[[sections.items]]
content = """
英文题目，英文作答（不会涉及到复杂的英语表达）。开卷，可带计算器。难度适中，但没有计算器的情况下计算量稍大。
英文题目。
"""

[[sections]]
title = "关于实验"

[[sections.items]]
content = "注意实验报告需要用英文撰写。"
